/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn bitpolymul_simple(
        c: *mut u64,
        a: *const u64,
        b: *const u64,
        n_64: ::std::os::raw::c_uint,
    );
}
extern "C" {
    pub fn bitpolymul_2_128(
        c: *mut u64,
        a: *const u64,
        b: *const u64,
        n_64: ::std::os::raw::c_uint,
    );
}
extern "C" {
    pub fn bitpolymul_2_64(c: *mut u64, a: *const u64, b: *const u64, n_64: ::std::os::raw::c_uint);
}
