/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn btfy_128(fx: *mut u64, n_fx: ::std::os::raw::c_uint, scalar_a: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn i_btfy_128(fx: *mut u64, n_fx: ::std::os::raw::c_uint, scalar_a: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn btfy_64(fx: *mut u64, n_fx: ::std::os::raw::c_uint, scalar_a: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn i_btfy_64(fx: *mut u64, n_fx: ::std::os::raw::c_uint, scalar_a: ::std::os::raw::c_uint);
}
