/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn encode_128_half_input_zero(
        rfx: *mut u64,
        fx: *const u64,
        n_fx_128b: ::std::os::raw::c_uint,
    );
}
extern "C" {
    pub fn encode_128(rfx: *mut u64, fx: *const u64, n_fx_128b: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn decode_128(rfx: *mut u64, fx: *const u64, n_fx_128b: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn encode_64_half_input_zero(rfx: *mut u64, fx: *const u64, n_fx: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn encode_64(rfx: *mut u64, fx: *const u64, n_fx: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn decode_64(rfx: *mut u64, fx: *const u64, n_fx: ::std::os::raw::c_uint);
}
